### PR TITLE
Set raw digit raise error

### PR DESCRIPTION
**Pull request by geekguy-wy**
Added checking that will raise an error for digit and bitmask value to Seg14x4.set_digit_raw()

### CODE REVIEW

**Comment by makermelissa** [comment]
Please rebase

**Review by makermelissa — CHANGES_REQUESTED** [review]
Please rebase

**Comment by dhalbert** [comment]
@makermelissa @geekguy-wy asked in discord about why you wanted a squash. I speculated it was just to reduce the number of commits. Is that right?

**Comment by makermelissa** [comment]
If you go into file changes, you'll notice a new file called `examples/ht16k33_animation_demo.py`, however that was already added in another PR by @geekguy-wy. It probably doesn't make a difference, but it's harder to review changes when it has duplicate commits.

**Comment by geekguy-wy** [comment]
So, do I or do I not do 'git rebase' in my repo??

**Comment by makermelissa** [comment]
Closing. Manually merged.

**Pull request closed without merging**
