### PR TITLE
Added Shift functions for matrix

### PR DESCRIPTION
**Pull request by makermelissa**
Taking full advantage of the refactored matrix classes, I ported these functions over from the FeatherWing library so we can use them with non-feather matrices. This also allows the read the matrix dimensions for calculations.

### CODE REVIEW

**Comment by ladyada** [comment]
make a generic shift x y function?

**Comment by makermelissa** [comment]
I'll see what I can do. :)

**Comment by makermelissa** [comment]
I'm not sure if this is what you meant. I can remove the shift_up, etc. functions if you think that would be better.

**Review by ladyada — APPROVED** [review]
yeah!

**Pull request merged**
