### PR TITLE
Adding demos and tests

### PR DESCRIPTION
**Pull request by geekguy-wy**
I added ht16k33_matrix_pillow_image.py (missing) and ht16k33_animation_demo.py (new) to the docs/examples.rst file, which is now current.

### CODE REVIEW

**Review by makermelissa — COMMENTED** [review]
Since you are linking to the animation demo, I'll wait until that is merged. However, you may need to rebase after that so there's no merge conflict.

**Comment by geekguy-wy** [comment]
I am happy with this version as is.

**Comment by geekguy-wy** [comment]
https://github.com/adafruit/Adafruit_CircuitPython_HT16K33/issues/57

**Review by makermelissa — APPROVED** [review]
Thanks for adding this

**Pull request merged**
