### PR TITLE
change to property style access

### PR DESCRIPTION
**Pull request by caternuson**
Some progress for #2. Changes to property style access for `brightness` and `blink_rate`. Also adds index style access to pixels.
```python
import board, busio
from adafruit_ht16k33 import matrix
i2c = busio.I2C(board.SCL, board.SDA)
matrix = matrix.Matrix8x8(i2c)

matrix.fill(0)
matrix.brightness = 8
matrix.blink_rate = 2
matrix[2,6] = 1
matrix.show()
```

### CODE REVIEW

**Comment by tannewt** [comment]
What guides and examples need updating as well?

**Comment by caternuson** [comment]
The example in README.rst - just did this, so it's in PR now.

The CP section of this guide:
https://learn.adafruit.com/micropython-hardware-led-backpacks-and-featherwings/circuitpython

**Comment by tannewt** [comment]
Ok, thanks for the link! @caternuson do you have edit rights to the guide to update it?

**Comment by caternuson** [comment]
Looks like I have edit rights. I shall update.

**Pull request merged**
