### PR TITLE
Constructor brightness parameter

### PR DESCRIPTION
**Pull request by geekguy-wy**
I added a new brightness=1.0 parameter to the HT16K33 constructor to allow brightness to be set on instantiation. The default is the same as it was before this change to stay consistent and not offer any surprises.

### CODE REVIEW

**Comment by geekguy-wy** [comment]
Addresses issue #70

**Review by makermelissa — APPROVED** [review]
This looks great! Thank you. Since this will break code, I want to wait on merging until I update at least one library that I know will break from this change.

**Comment by geekguy-wy** [comment]
The default for the new brightness parameter is the same as it was before this change.  There should not be any breakage of code. All current calls will remain the same because the brightness parameter is not required.

**Comment by makermelissa** [comment]
Code such as https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/BLE_Heart_Rate_Trainer/ble_heart_rate_trainer.py will need to be updated as it would error after this change.

**Comment by geekguy-wy** [comment]
You can still create an instance with the existing parameters. You do not have to add the brightness parameter - the default is the same as before I made this change.

If you are talking about the change to using a float instead of an int for the brightness value, then that would break code.

**Comment by makermelissa** [comment]
Yes, that's what I was referring to.

**Pull request merged**
