### PR TITLE
Fixed Flicker for Numbers when Autowrite is on

### PR DESCRIPTION
**Pull request by makermelissa**
Fixed Flicker for Numbers when Autowrite is on

See https://github.com/adafruit/Adafruit_CircuitPython_HT16K33/issues/29

### CODE REVIEW

**Comment by makermelissa** [comment]
I also tested that this didn't break the work I did for Adafruit_CircuitPython_FeatherWing. 

Note: This was only tested on the 14-Segment display as that's all I have at the moment.

**Comment by caternuson** [comment]
That will cover it for an actual number input:
```python
disp.print(1234)
```
but not for string:
```python
disp.print("1234")
```
Take a look at how `print()` routes to either `_text` or `_number`. For a string entry, it goes straight to `_text` and would bypass the `auto_write` disable in `_number`.

How about:
* remove auto_write lines from `_put` in all classes
* add them to end of `__setitem__`

**Comment by makermelissa** [comment]
Yeah, I especially noticed it with the numbers. I'll go ahead and experiment with it some more and write a little test script that can work for strings too. Something along the lines of:
```
count = 1000
while count < 9000:
    count += 1 
    display.print("{}".format(count))
    time.sleep(0.1)
```
That should make any flickering pretty evident.

**Comment by makermelissa** [comment]
I did as you suggested and it looks good so far. I want to test some more before I call it good.

**Comment by caternuson** [comment]
Cool. Ping me when you're ready for another look. I've got the other displays and can test them.

**Comment by makermelissa** [comment]
Yep @caternuson. It's ready for you to take another look.

**Comment by caternuson** [comment]
Let's good. Tested and working on a 7 segment.

Thanks for the fix.

**Pull request merged**
