### PR TITLE
Removed artifical limiting of 7x4 display (LOL)

### LINKED ISSUE #79: No LOL'ing with 7x4 Segment
Seg7x4 is feeling a bit unloved (:broken_heart: & :cry:) and could really do with a laugh to feel a bit better.  However, L,l,O,o are prohibited characters and silently dropped.

Please help put a smile on Seg7x4's face. :laughing:

### PR DESCRIPTION
**Pull request by Daviey**
I needed more LOL'ing in my life, and a 7x4 segment display can help
with this.

However, adafruit_ht16k33 filters this out for the 7x4 display which
makes me super sad :cry:.  This change allows the use of both upper and
lower case L's and O's.

(also, matrix.py and segments.py had the eXecutable bit set, which has
been dropped)

Fixes: adafruit/Adafruit_CircuitPython_HT16K33#79
Signed-off-by: Dave Walker (Daviey) <email@daviey.com>

### CODE REVIEW

**Comment by deshipu** [comment]
I wonder what is your use case for this? If you need to display arbitrary patterns, then just use a lower-level interface.

**Comment by Daviey** [comment]
> I wonder what is your use case for this? If you need to display arbitrary patterns, then just use a lower-level interface.

I wanted to use `marquee()`, which internally uses `print()` which means it can't use the lower level interface `set_digit_raw()` with `marquee()`.  If `marquee()` can start supporting `set_digit_raw()` - then that would be great.

**Comment by deshipu** [comment]
Sounds like a good idea: either extending the marquee to work with arbitrary patterns, or writing a version that does strikes me as a cleaner and more general solution.

**Review by FoamyGuy — APPROVED** [review]
I've created #94 to open up the idea of extending marquee to work with set digits raw.

I also merged main into this PR branch to get it passing the CI.

Tested the changes successfully with RP2040 and 7x4 featherwing.

I think it's okay to merge it this way for now. If in the future someone makes a more general way to place other text characters or arbitrary patterns into the marquee then we can remove the code specific to `l` and `o` here.

**Pull request merged**
